### ISSUE TITLE
[Custom]: I broke my system and theme switching and wallpaper is broken

### ISSUE THREAD

**Issue by its-19818942118** [prasanthrangan/hyprdots#1175] opened 2024-03-24 16:08 UTC
### Description

[Provide a clear and concise description of the issue or request.]

![image](https://github.com/prasanthrangan/hyprdots/assets/87006850/a71484d8-f1d1-421b-a497-5a986c6043ae)

### Steps to Reproduce (if applicable)

idk if it will work or not.

1. [sudo pacman -Syy sudo pacman -Scc sudo pacman -Suu]
2. [power outage wifi gone]
3. [pacman stopped]
4. [system ram full system stop]
5. [theme and wallpaper dead applying theme logout and login]

**Comment by dei0ces** [comment] 2024-03-24 16:11
same after I did cd ~/Hyprdots/Scripts
git pull
./install.sh -r today

**Comment by its-19818942118** [comment] 2024-03-24 17:14
wait maybe thats why my system broke .... and not due to updates cuz pacman is pretty chill

**Comment by Enigma1309** [comment] 2024-03-24 18:28
It's a swww problem, updating to the latest version or switching to swww-git is the solution to the problem

Also make sure you have updated your hyprdots setup (especially this commit https://github.com/prasanthrangan/hyprdots/commit/16b28ffff0ee7ab58fb3e816c27066827f861e19)

**Comment by dei0ces** [comment] 2024-03-24 18:50
using swww-git now, most of the problems are gone but wallbash is not working rn. if I activate wallbash everything is breaking again

**Comment by kRHYME7** [comment] 2024-03-24 23:55
> using swww-git now, most of the problems are gone but wallbash is not working rn. if I activate wallbash everything is breaking again

``` Hyprdots rebuild cache ```

**Comment by joserg10** [comment] 2024-03-25 00:49
The problem is that the colors configuration was lost in /.config/hypr/themes/colors.conf.
And other problem is that weybar is not workin after the last update

**Comment by Rayout-Py** [comment] 2024-03-25 01:21
Same happening for me. Have tried clearing swww cache, rebuilding and everything else everyone suggested. Nothing. Still same as the screen shot above. Then crashes back to the greeter login.

**Comment by its-19818942118** [comment] 2024-03-25 05:09
broo these are all way to complicated. i am a noob to everything here. pls provide instructions

**Comment by its-19818942118** [comment] 2024-03-25 07:34
well i tried everything. i am a noob so i think i missed somethings. but pls fix this quickly. i hate it breaking my wallpaper. rofi works fine and all but the wallpaper just breaks.

**Comment by kRHYME7** [comment] 2024-03-25 08:16
@its-19818942118  You still got the  the issue were wallpaper becomes gray?

what is your swww version ? ``` yay -Qs swww ```

**Comment by its-19818942118** [comment] 2024-03-25 09:58
swww and swww-debug both are 0.9.1-1


> @its-19818942118 You still got the the issue were wallpaper becomes gray?
> 
> what is your swww version ? `yay -Qs swww`

**Comment by its-19818942118** [comment] 2024-03-25 10:01
@kRHYME7 update wallpaper is gray and distorted but. switching works. theme is broken. rofi is working and is unfazed what so ever.

**Comment by kRHYME7** [comment] 2024-03-25 11:08
have your tried  installing the development version of swww? ``` yay -Sy swww-git ``` installation would take time then reboot.

**Comment by dei0ces** [comment] 2024-03-25 11:09
> > using swww-git now, most of the problems are gone but wallbash is not working rn. if I activate wallbash everything is breaking again
> 
> 
> 
> ``` Hyprdots  cache rebuild ``` 

thanks

**Comment by its-19818942118** [comment] 2024-03-25 22:01
> have your tried installing the development version of swww? `yay -Sy swww-git` installation would take time then reboot.

Can't bro doesn't allow

**Comment by nicolkrit999** [comment] 2024-03-25 23:32
> > have your tried installing the development version of swww? `yay -Sy swww-git` installation would take time then reboot.
> 
> 
> 
> Can't bro doesn't allow

It probably tells you there is a conflict. If you type n then it does nothings. Just press enter or type "y" when prompted for the conflict

**Comment by its-19818942118** [comment] 2024-03-26 06:46
broo i did it just doesnt install saying dependencies break etc

**Comment by its-19818942118** [comment] 2024-03-26 06:52
```
error: failed to commit transaction (conflicting files)
swww-git-debug: /usr/lib/debug/usr/bin/swww-daemon.debug exists in filesystem (owned by swww-debug)
swww-git-debug: /usr/lib/debug/usr/bin/swww.debug exists in filesystem (owned by swww-debug)
Errors occurred, no packages were upgraded.
 -> error installing: [/home/izumi/.cache/yay/swww-git/swww-git-0.4.0.r319.gdcf0d4e-1-x86_64.pkg.tar.zst /home/izumi/.cache/yay/swww-git/swww-git-debug-0.4.0.r319.gdcf0d4e-1-x86_64.pkg.tar.zst] - exit status 1
```
my error when installing swww-git

**Comment by dei0ces** [comment] 2024-03-26 06:56
> ```
> 
> error: failed to commit transaction (conflicting files)
> 
> swww-git-debug: /usr/lib/debug/usr/bin/swww-daemon.debug exists in filesystem (owned by swww-debug)
> 
> swww-git-debug: /usr/lib/debug/usr/bin/swww.debug exists in filesystem (owned by swww-debug)
> 
> Errors occurred, no packages were upgraded.
> 
>  -> error installing: [/home/izumi/.cache/yay/swww-git/swww-git-0.4.0.r319.gdcf0d4e-1-x86_64.pkg.tar.zst /home/izumi/.cache/yay/swww-git/swww-git-debug-0.4.0.r319.gdcf0d4e-1-x86_64.pkg.tar.zst] - exit status 1
> 
> ```
> 
> my error when installing swww-git

try first deleting swww and then install swww-git

sudo pacman -R swww swww-debug && sudo pacman -Syyu swww-git

**Comment by its-19818942118** [comment] 2024-03-26 07:46
@dei0ces broo what to after that?

**Comment by its-19818942118** [comment] 2024-03-26 07:48
i cant seem to delete swww

**Comment by dei0ces** [comment] 2024-03-26 07:49
> @dei0ces broo what to after that?

reboot
and 
Hyprdots cache rebuild

then

cd ~/Hyprdots/Scripts
git pull
./install.sh -r

if the second doesnt finish, do it again. it didnt finish in my first attempt, write 

cd ~/Hyprdots/Scripts
git pull
./install.sh -r
again

**Comment by dei0ces** [comment] 2024-03-26 07:51
> i cant seem to delete swww
> 
> 

why? try 
pacman -Rd --nodeps swww swww-debug

**Comment by its-19818942118** [comment] 2024-03-26 07:57
lol when deleting it says swww and .... target not found when using pacman and yay

**Comment by dei0ces** [comment] 2024-03-26 07:58
> lol when deleting it says swww and .... target not found when using pacman and yay

nice so you removed it,
now install yay -Syyu swww-git

**Comment by nicolkrit999** [comment] 2024-03-26 08:21
> lol when deleting it says swww and .... target not found when using pacman and yay

-Rd --nodepa remove a package and skip dependencies check. Only do that in cases like this where you are 100% sure that the packages you install after is compatible with every program you have and or/is better than the existing one. Also always remove and reinstall in the same boot. If you skip dependencies check then reboot you may not even be able to login back again if what you removed is a big part of the operating system

**Comment by its-19818942118** [comment] 2024-03-26 08:22
> > lol when deleting it says swww and .... target not found when using pacman and yay
> 
> nice so you removed it, now install yay -Syyu swww-git

wait so it got removed

**Comment by nicolkrit999** [comment] 2024-03-26 08:27
> > > lol when deleting it says swww and .... target not found when using pacman and yay
> 
> > 
> 
> > nice so you removed it, now install yay -Syyu swww-git
> 
> 
> 
> wait so it got removed

Yes since it tells you the target does not exist, this means there is nothing to perform actions on. Just install now the git version

**Comment by its-19818942118** [comment] 2024-03-26 08:28
oh i am so stupid

**Comment by its-19818942118** [comment] 2024-03-26 08:28
> > lol when deleting it says swww and .... target not found when using pacman and yay
> 
> nice so you removed it, now install yay -Syyu swww-git

then what

**Comment by dei0ces** [comment] 2024-03-26 08:29
> > > lol when deleting it says swww and .... target not found when using pacman and yay
> 
> > 
> 
> > nice so you removed it, now install yay -Syyu swww-git
> 
> 
> 
> then what

reboot
and
Hyprdots cache rebuild

then

cd ~/Hyprdots/Scripts
git pull
./install.sh -r

if the second doesnt finish, do it again. it didnt finish in my first attempt, write

cd ~/Hyprdots/Scripts
git pull
./install.sh -r
again

**Comment by its-19818942118** [comment] 2024-03-26 09:07
aight thanks problem fixed

**Comment by joserg10** [comment] 2024-03-26 14:47
Well in the last update of hyprland and swww-git the problem was solved rebuilding cache

**Comment by kRHYME7** [comment] 2024-03-26 14:59
@sandeng

**Comment by DiegoSof2** [comment] 2024-03-26 17:07
I also have this problem

![240326_14h06m46s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/105827698/fdd8be5d-07a9-46da-bbc0-a8352ecab13d)

**Comment by its-19818942118** [comment] 2024-03-27 15:33
> I also have this problem
> 
> ![240326_14h06m46s_screenshot](https://private-user-images.githubusercontent.com/105827698/316967968-fdd8be5d-07a9-46da-bbc0-a8352ecab13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTM2NzYsIm5iZiI6MTcxMTU1MzM3NiwicGF0aCI6Ii8xMDU4Mjc2OTgvMzE2OTY3OTY4LWZkZDhiZTVkLTA3YTktNDZkYS1iYmMwLWE4MzUyZWNhYjEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxNTI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDlhZDFlNjRiNzdjYjk3ZjY4YzExN2M3ZDQwZTUxNDdhODVlOWVlNzc1NzUwYzEzYzhlNjYwMjA3YTkyOTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t0LAhnqzsDHZuESUep4fGgpIoO_nPI6zrsPwTCcCqqw)

follow these steps to resolve the issue
```
# remove swww
sudo pacman -R swww swww-debug
```
```
yay -S swww-git
```
then
```
# reboot
and
Hyprdots cache rebuild

# then

cd ~/Hyprdots/Scripts
git pull
./install.sh -r

# if the second doesnt finish, do it again. it didnt finish in my first attempt, write

cd ~/Hyprdots/Scripts
git pull
./install.sh -r
# again
```
that should fix the issue

**Comment by DiegoSof2** [comment] 2024-03-27 18:48
> @DiegoSof2
> 
> > I also have this problem
> > ![240326_14h06m46s_screenshot](https://private-user-images.githubusercontent.com/105827698/316967968-fdd8be5d-07a9-46da-bbc0-a8352ecab13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTM2NzYsIm5iZiI6MTcxMTU1MzM3NiwicGF0aCI6Ii8xMDU4Mjc2OTgvMzE2OTY3OTY4LWZkZDhiZTVkLTA3YTktNDZkYS1iYmMwLWE4MzUyZWNhYjEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxNTI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDlhZDFlNjRiNzdjYjk3ZjY4YzExN2M3ZDQwZTUxNDdhODVlOWVlNzc1NzUwYzEzYzhlNjYwMjA3YTkyOTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t0LAhnqzsDHZuESUep4fGgpIoO_nPI6zrsPwTCcCqqw)
> 
> follow these steps to resolve the issue
> 
> ```
> # remove swww
> sudo pacman -R swww swww-debug
> ```
> 
> ```
> yay -S swww-git
> ```
> 
> then
> 
> ```
> # reboot
> and
> Hyprdots cache rebuild
> 
> # then
> 
> cd ~/Hyprdots/Scripts
> git pull
> ./install.sh -r
> 
> # if the second doesnt finish, do it again. it didnt finish in my first attempt, write
> 
> cd ~/Hyprdots/Scripts
> git pull
> ./install.sh -r
> # again
> ```
> 
> that should fix the issue

solved part of the problem now I can change the theme and wallpaper before the screen was going black when doing this, however the laptop screen still has a distorted and black and white image, as shown in the image below

![image](https://github.com/prasanthrangan/hyprdots/assets/105827698/5dbbfeb2-23a3-46a6-8215-52f57470ee8d)

**Comment by kRHYME7** [comment] 2024-03-28 00:06
@DiegoSof2  A Swww upstream bug. https://github.com/LGFae/swww/issues/233

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/b1651fd0-0ded-41a5-868b-c640fbb7e2a6)


please be sure that you are using this very line

``` swww-daemon --format xrgb &```

**Comment by DiegoSof2** [comment] 2024-03-28 16:37
> swww-daemon --format xrgb &
yes it is correct

![image](https://github.com/prasanthrangan/hyprdots/assets/105827698/6a555faa-b4a8-476c-be95-378de4ac6105)

**Comment by its-19818942118** [comment] 2024-04-01 06:32
Aight so problem fixed?

**Comment by kRHYME7** [comment] 2024-04-01 07:03
We can close this as unrelated as the issue is from the upstream swww repo. https://github.com/LGFae/swww/commits/main/
for now, For newcomers, you guys can follow the instructions I posted at #1204.

Maybe someone can help to solve this, here is the upstream issue
https://github.com/LGFae/swww/issues/233 
(dev is planning to refactor the project, so would take some time to have the stable one)

**Closed by kRHYME7** 2024-04-01 07:03 UTC
