### ISSUE TITLE
[Bug]: waybar crashing intermittently

### ISSUE THREAD

**Issue by Acebasein** [prasanthrangan/hyprdots#1228] opened 2024-04-01 02:16 UTC
Hello,

I have been observing intermittent crashing of waybar for the past few days. Noticed "waybar crashing" issue after the installation of the below theme, I suspect.  Please help:

1. Ran Theme Patcher as described to install "Synth-Wave" theme - https://github.com/prasanthrangan/hyprdots/wiki/Theming
`cd ~/Hyprdots/Scripts # hyprdots clone directory`
`./themepatcher.sh "Synth-Wave" "$HOME/Patch/Synth-Wave" "robbowen.synthwave-vscode~SynthWave '84"`

2. Tried updating the repo as below to see if the issue gets resolved:
`cd ~ && cd Hyprdots `
`git pull`
`cd Scripts`
`./install.sh -r`
This update removed the newly installed theme "Synth-Wave". However, this issue still persists.

3. Invoked waybar thru terminal and captured the error. Please see below

> ❯ waybar
[2024-03-31 21:42:00.842] [info] Using configuration file /home/ace/.config/waybar/config.jsonc
[2024-03-31 21:42:00.844] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
[2024-03-31 21:42:00.844] [info] Using CSS file /home/ace/.config/waybar/style.css
[2024-03-31 21:42:00.860] [info] Hyprland IPC starting
[2024-03-31 21:42:00.861] [info] Loading persistent workspaces from Waybar config
[2024-03-31 21:42:00.861] [info] Loading persistent workspaces from Hyprland workspace rules

> ** (waybar:5366): WARNING **: 21:42:01.024: Status Notifier Item with bus name ':1.26' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
> [2024-03-31 21:42:01.038] [warning] Requested height: 31 is less than the minimum height: 32 required by the modules
> [2024-03-31 21:42:01.038] [info] Bar configured (width: 1280, height: 32) for output: eDP-1
> 
> ** (waybar:5366): WARNING **: 21:42:02.410: Status Notifier Item with bus name ':1.26' and object path '/org/ayatana/NotificationItem/nm_applet' is already registered
> 
> (waybar:5366): Gdk-CRITICAL **: 21:42:23.691: gdk_wayland_window_get_wl_surface: assertion 'GDK_IS_WAYLAND_WINDOW (window)' failed
> Gdk-Message: 21:42:23.692: Error 22 (Invalid argument) dispatching to Wayland display.

CTRL+Esc  to toggle waybar is working but crashes with same error again and again. System info is here:
![240331_22h04m00s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/165613042/547fcc0f-2da9-4f1a-a226-185a06cf31fc)

**Comment by simplemachine-zz** [comment] 2024-04-01 13:38
I noticed that my waybar always close when i move to another workspace or for a random reason. I hope it gets fixed.

**Comment by kRHYME7** [comment] 2024-04-01 15:05
@simplemachine-zz  Try to add this on your user prefs ``` general:no_cursor_warps=1 ``` 

Also, the issue is from upstream waybar. So to be able to fix this, please open an issue there. (Waybar's too buggy 😭 ) But the above workaround should fix it.

**Comment by Acebasein** [comment] 2024-04-01 16:00
> @simplemachine-zz Try to add this on your user prefs `general:no_cursor_warps=1`
> 
> Also, the issue is from upstream waybar. So to be able to fix this, please open an issue there. (Waybar's too buggy 😭 ) But the above workaround should fix it.

Thank you @simplemachine-zz . Added the instruction in my config file and it seems working so far. No more crashes reported after that :+1:

**Comment by nonme** [comment] 2024-04-03 12:59
> @simplemachine-zz Try to add this on your user prefs `general:no_cursor_warps=1`
> 
> Also, the issue is from upstream waybar. So to be able to fix this, please open an issue there. (Waybar's too buggy 😭 ) But the above workaround should fix it.

It seems to work and is a very nice settings by itself, thanks man. However it still crashes sometimes if you drag (or drag by accident) app's icon on the waybar to rearrange it. Hope it will be fixed soon since I also started to encounter this after sudo pacman -Syu.

**Closed** 2024-04-15 16:53 UTC
Labels: bug
