### ISSUE TITLE
Error while installing extensions: connect ETIMEDOUT 2620:1ec:a92::175:443

### ISSUE THREAD

**Issue by noro-gamser** [prasanthrangan/hyprdots#651] opened 2023-12-15 01:50 UTC
Hey,
 
 I get this issue:
 
Installing extensions...
Error while installing extensions: connect ETIMEDOUT 2620:1ec:a92::175:443
connect ETIMEDOUT 2620:1ec:a92::175:443

Thank you

**Comment by Skerse** [comment] 2023-12-15 01:59
Duplicate of https://github.com/prasanthrangan/hyprdots/issues/650

Plan to figure out the issue, but i'll have to reinstall my desktop, so sorry if it takes some time to get a fix in! Hopefully i'll have a fix in the next 6 hours.

**Comment by kRHYME7** [comment] 2023-12-15 03:18
isn't this a connection timeout issue maybe with the internet or the server? Might try to figure this out too..

**Comment by kRHYME7** [comment] 2023-12-15 03:33
> Plan to figure out the issue, but i'll have to reinstall my desktop every time to test


Hey mate! @Skerse   I already added ``` Hyprdots restore BackUp ```  on Hyprdots-ctl it will recursively restores a backup . Also to be safe ``` Hyprdots backup all ``` might be better so you could restore your explicit backups  ``` Hyprdots backup revert ``` 
.
Maybe you can try it out.

**Comment by Skerse** [comment] 2023-12-15 05:08
Well i was expecting when Hyprdots finished downloading that it would break, but it didn't so now i'm confused.

However, i want to look into these deprecation warnings here: 
![image](https://github.com/prasanthrangan/hyprdots/assets/139541046/3eec1b41-315e-4194-ab93-707433e3a521)

**Comment by kRHYME7** [comment] 2023-12-15 05:23
It was just a warning though, I think OP has internet connectivity issues.

**Comment by prasanthrangan** [comment] 2023-12-15 16:03
Hey, this is not an issue with the install script, its just warnings and the extension is installed successfully.
I'll update the script to redirect the warnings to keep it clean!

> Error while installing extensions: connect ETIMEDOUT 2620:1ec:a92::175:443
> connect ETIMEDOUT 2620:1ec:a92::175:443

This seems to be an issue with the network or temporary issue with the extension marketplace itself.

**Comment by noro-gamser** [comment] 2023-12-15 23:30
Thank you all for the replies, today I was able to install it. 

Oh sorry, half of my text is missing, I haven´t notice it yesterday.

@Skerse @kRHYME7 @prasanthrangan Thank you guys

I run few 5-6 different installations in VMs, on 2 different host systems yesterday and always got the same issue. (Host system Proxmox 8, trying to get Arch running with a GVT-g). 

The only difference the host systems have is the DNS, one use PiHole and the other use DNS from ISP, it stuckend always at the same. May it was some kind IPv6 issue in my network that Im not aware of it, all other stuff runs only IPv4, except this few VM´s and mobile phones. 

I will close this as fixed.

**Closed** 2023-12-15 23:32 UTC
Labels: unrelated
