### ISSUE TITLE
[solved] [Bug]: unable to change wallpaper, themes and there is no command as Hyperdots

### ISSUE THREAD

**Issue by icoderarely** [prasanthrangan/hyprdots#1305] opened 2024-04-13 23:28 UTC
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

`Super + Shift + T` and `Super + Shift + W` does open theme select and wallpaper select menu as expected. But when I click on it, or press enter it doesnt change my theme or wallpaper.
Even the leftmost 3 buttons Switch bar/theme/wallpaper dont seem to respond.

I found some issues where they were recommending to use `Hyprdots` as command, but for me it gives not found. 

### Expected Behavior

It should change the theme/wallpaper. And Hyprdots if is a command should work

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: ArchLinux
- Linux Version, output of `uname -a`: 6.8.5-arch1-1
- Hyprland Version, output of `hyprctl version`: v0.38.1-b
- Installation Environment: Main Hardware
- Other info: Display Resolution (1920x1080)

I tried to check for `cat ~/.config/hypr/theme.ctl` but no such file is what I got - [Found a similar issue where it was discussed]

There was nothing on this link too https://github.com/prasanthrangan/hyprdots/blob/main/Configs%2F.config%2Fhypr%2Ftheme.ctl

**Comment by icoderarely** [comment] 2024-04-13 23:37
Okay so I rebooted my device and I was able to change themes and wallpapers. 
But now choosing a theme, like I chose Decay-Green I expected the waybar to change too but it remains unchanged. Why so? 
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/ccbc911f-9922-44e3-9be9-04ddcf19293f)

**Comment by Enigma1309** [comment] 2024-04-14 05:09
you have to edit the module present inside `~/.config/waybar/modules/`
for custom size edit `~/.config/waybar/config.ctl`
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/45f7b05d-cacd-44e5-ba80-ab9d1e080bf6)
the second field is size.
for module spacing try editing `~/.local/share/bin/wbarstylegen.sh`
![image](https://github.com/prasanthrangan/hyprdots/assets/94917588/f6dafc5a-dbb7-4272-acd5-cb53a39e8230)
(in above image i have my custom parameters, for 24 inch display (1080p))

try editing and fiddling around with values
(there may be an easier approach to this, i'm not aware of, if anyone knows kindly comment here)

**Comment by icoderarely** [comment] 2024-04-14 06:12
i have these
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/104ad385-ec5b-404f-95fa-9470b3615943)

and i tried changing them but it doesnt seem to work.

as you can see the spacing and size is very less here, like i can see in my monitor i am not sure if its clear enough in a picture but still 
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/b3aeccc2-abf8-4f0c-96c8-9a49f2d4f177)

![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/478698bf-1bd2-4da7-be24-3a7e2f373e50)
This looks better comparatively, on same configs

here is the complete waybar
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/86b81774-8fa2-470f-97e6-ce20ad075f64)


`Also why doesnt, decay-green have a greenish effect, or look similar to the one as present` 
https://github.com/prasanthrangan/hyprdots?tab=readme-ov-file#-decay-green
Though my dolphin opens in similar color.

**Comment by kRHYME7** [comment] 2024-04-14 06:19
To have a dynamic waybar changes upon saving you can run this first 

``` Hyde waybar control ``` 

Then the code editor will open. When you save changes, it will dynamically regenerate the configs

**Comment by icoderarely** [comment] 2024-04-14 06:21
for me it says `/usr/lib/hyde-cli/GLOBAL_hyde: line 158: /home/user/.cache/hyde/hyde.meta: No such file or directory`

**Comment by kRHYME7** [comment] 2024-04-14 06:25
can you update that tool first? ``` yay -Sy hyde-cli-git ``` 

It should not ask for that file though when you run ``` Hyde waybar control ```

**Comment by icoderarely** [comment] 2024-04-14 06:28
I updated the tool as asked by you.

Still I get the same, here is an attachment
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/690582a0-bc1d-4043-8d42-237ca4deb5bb)

**Comment by kRHYME7** [comment] 2024-04-14 06:36
My bad  can you update  it again? https://github.com/kRHYME7/Hyde-cli/commit/b7371e1a72462b0ebede81a1c1a13ed236733d9b
 
Fixed this regression

**Comment by icoderarely** [comment] 2024-04-14 06:38
okay so this seems to work, but I dont know where to go from here
opens me this
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/5a91aa26-1b19-4b14-b71e-2641c7c6975e)

**Comment by icoderarely** [comment] 2024-04-14 06:45
Both Dolphin and the Rofi menu are currently open simultaneously. Dolphin displays its expected greenish colors, but Rofi and Waybar do not. I hope that clarifies things for point 3 in previous reply.
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/eca77615-4919-4557-b8f3-e5ad11e81416)

**Comment by kRHYME7** [comment] 2024-04-14 06:47
okay  saw a fix to this problem (let's ignore this first)

1. follow @Enigma1309  instructions
2. Play arounf the ctl file try adding spaces by encasulating the modules
example 
```
1|28|top|( hyprland/workspaces wlr/taskbar         ) (      hyprland/window )|( idle_inhibitor )  ( custom/roman_clock custom/updates custom/keybindhint )|( tray network bluetooth pulseaudio pulseaudio#microphone battery custom/gpuinfo )

```
They will be evenly spaced
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/3b3d0475-3154-44ae-a59c-e3f951ab80d4)

3. run ``` Hyde wallbash mode 0 ```
what happens?

**Comment by icoderarely** [comment] 2024-04-14 06:58
1. I am not sure what all needs to be changed and to what
2. Same here, I tried looking for a line similar to yours but unfortunately not there
3. this gives me an error, it did do some changes i believe to the waybar
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/92fac739-c6b3-4a6a-9d22-d9c5f6ba9a54)

**Comment by kRHYME7** [comment] 2024-04-14 07:18
You can ignore those errors but ``` yay -Sy libnotify ``` is a must package. This is a notification utility .

1. change the second field that is the scaling 
2.  just encapsulate the module to isolate the spaces. find the line with 1 at the first field that is the active waybar layout 
3. wallbash is script we use to dynamically change color pallettes based on the current wallpaper.

**Comment by icoderarely** [comment] 2024-04-14 07:27
1. 2. So changing the value after `1:*` did fix both.
3. Oh I see, so earlier I had a blackish some wallpaper so black waybar colors, but now I changed it to green one but still the same, no change.

**Comment by kRHYME7** [comment] 2024-04-14 07:38
Try to change themes

**Comment by icoderarely** [comment] 2024-04-14 07:41
Except for Edge Runner all have the same waybars styles?

**Comment by kRHYME7** [comment] 2024-04-14 07:56
If you want to inspect per theme specific, try to disable wallbash first ``` Hyde wallbash mode 0 ```

 The layout will not change as it is bound to the config.ctl but the style does 
 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/42f8eed2-908f-4727-b230-be835405980d)
 
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/bf12759f-8cc2-4c5c-b0f5-46b6e715eece)

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/0f0833c7-8072-491f-9d45-f6e5291e3efc)

Mostly have the same curves but you can modify it per theme

**Comment by icoderarely** [comment] 2024-04-14 20:48
Oh I see, and the modification can be done in which file? that it persists.

Also if there is an update in Hyprdots, and I update it will that also reset all the changes made in any of the configs?

**Comment by kRHYME7** [comment] 2024-04-14 23:55
MB, it's not actually a full waybar config though.

![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/24751604-e17f-4b06-a50f-3cfe7b7110a8)
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/4b7a0f27-574e-486b-9adf-7b811881ca68)

So the wbarstylegen script fetches the rounding value of the hyprland config. Then it is use as waybar rounding too. Ig for now that's what it can do per theme. 

 > Also if there is an update in Hyprdots, and I update it will that also reset all the changes made in any of the configs?
 
 Nope the themes are isolated now, therefore changes inside ~/.config/hyde/themes* won't be touch.
 
 Manage Config changes by ``` Hyde restore Config ```

**Comment by icoderarely** [comment] 2024-04-15 13:38
I meant in general like if for example currently I am using dual monitors and nvidia.conf as well, so once you release an update will those be lost? And I have to restore it or rewrite it again? 
Cause I had a similar issue with a hyprland config of some other author previously too, and that was frustrating.

**Comment by kRHYME7** [comment] 2024-04-15 13:56
All the layouts are stored at ```  ~/.config/waybar/config.ctl ``` so better to save this .
Even if the configs are overwritten, it will be backed up at ```  ~/.config/cfg_backups ``` .

Keep in mind we are all sharing our own .config/dotfiles so it surely is intended to overwrite your configs or something might not work. We are not on a full fledge DE that stores the defaults in another space.

I wrote a utility to interactively manage the configs so you can set what to preserve , overwrite etc. 
``` Hyde restore Config ```
![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/dc6f85a9-3c5d-420a-832e-621fd702e529)

**Comment by icoderarely** [comment] 2024-04-15 18:39
sounds great, will surely try this on next release of hyprdots

**Comment by icoderarely** [comment] 2024-04-16 16:29
i am not sure how/why but all of a sudden when i just clicked on switch bar it just changed how it looks
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/645125d4-bb84-43be-96b6-117335330ba8)
and this looks really bad to me, how to get back?

**Comment by icoderarely** [comment] 2024-04-16 16:30
and now to this
![image](https://github.com/prasanthrangan/hyprdots/assets/166960965/4654d64d-db66-4e89-bd5d-3968680028e2)

this time i used `super+alt+arrow`

**Comment by dieBakterie** [comment] 2024-04-16 16:32
Could can Change the bar with this keykomb Just use Arrow down or Up don't know what you pressed Press the opposite Arrow to get Back to the prevoius one until you've your desired bar again

**Comment by icoderarely** [comment] 2024-04-16 16:34
Just arrow up and down? I guess you mean `Super+Alt+Arrow`

**Comment by icoderarely** [comment] 2024-04-16 16:39
Alright fixed it somehow! I guess I have to keep doing this until satisfied `Super+Alt+Arrow`

**Comment by Enigma1309** [comment] 2024-04-16 17:00
super alt up/down arrow are for switching way-bar modes (styles)

you can also close this issue if it's fixed

**Closed** 2024-04-16 17:26 UTC
Labels: bug
