### ISSUE TITLE
[Bug]: Dolphin UI bug after recent update

### ISSUE THREAD

**Issue by rafaeljacov** [prasanthrangan/hyprdots#1087] opened 2024-03-15 06:37 UTC
### Description
I just did a system upgrade and then dolphin became ugly. See screenshot

### Screenshots
![image](https://github.com/prasanthrangan/hyprdots/assets/110229646/7504b329-7343-4666-a1c5-3e08f37b55b9)

**Comment by Enigma1309** [comment] 2024-03-15 07:03
Duplicate of https://github.com/prasanthrangan/hyprdots/issues/1030

**Closed** 2024-03-15 07:36 UTC
Labels: bug
