### ISSUE TITLE
The notification doesn't change after disabling wallbash

### ISSUE THREAD

**Issue by T3l3sc0p3** [prasanthrangan/hyprdots#497] opened 2023-11-15 15:48 UTC
Hi, I just realized that when I turn off the wallbash, the notification still keeps the wallbash even if I reboot or change to another theme

![image](https://github.com/prasanthrangan/hyprdots/assets/96990857/f6764473-23f4-450f-8908-b986972371df)

Is it a feature or a bug?

**Comment by T3l3sc0p3** [comment] 2023-11-15 16:28
Hmm, can you tell me where the notification window config is located? I think the problem may start from there ._.

**Comment by zer0cha0s** [comment] 2023-11-15 16:54
The dunst config is $HOME/.config/dunst.
There is a script wallbashdunst.sh which im assuming is in control of pushing the wallbash theme changes to it.

**Comment by devCKVargas** [comment] 2023-11-15 17:01
> Is it a feature or a bug?

It's a recent feature, check commit 368ad4d

**Comment by zer0cha0s** [comment] 2023-11-15 17:06
> > Is it a feature or a bug?
> 
> It's a recent feature, check commit [368ad4d](https://github.com/prasanthrangan/hyprdots/commit/368ad4da4ab268ebc179199c506c6db47b8e2119)

Its a feature that it changes using wallbash ill agree with that but if the theme is changed the notifications should change along with the theme should it not? 
If its getting stuck then is it not a bug ?

**Comment by devCKVargas** [comment] 2023-11-15 17:34
> Its a feature that it changes using wallbash ill agree with that but if the theme is changed the notifications should change along with the theme should it not? If its getting stuck then is it not a bug ?

It behaved as you would expect before the commit.
Notification colors matched the color of the active wallpaper, but only if wallbash was enabled.
I'm not a fan of this feature myself and will revert the said commit on my fork; I just haven't had the time to do so.

**Comment by prasanthrangan** [comment] 2023-11-18 11:47
Hi, this is not a bug, its supposed to change with wall...
Previously the colors were hardcoded and I didn't have time to create color configs for each theme :)
So I just integrated it with wallbash!

I'll close this issue as well...

**Closed by prasanthrangan** 2023-11-18 11:47 UTC
