### ISSUE TITLE
[Bug]: QT apps has a glitched and laggy drop down menu when using certain themes in wallbash "theme mode"

### ISSUE THREAD

**Issue by TheKamboy** [prasanthrangan/hyprdots#1719] opened 2024-07-31 04:34 UTC
### Description

I thought I would mention this issue here since [someone posted it in the hyde-themes repo](https://github.com/prasanthrangan/hyde-themes/issues/22), but no one other than me has seen it.

It seems to affect certain themes (All I know is that Dracula and Nord has the issue).

This probably affects me more since I don't have the most powerful computer, which causes the glitched drop down menu to lag Dolphin. 

### Steps to Reproduce

1. Use the latest release of Hyde
2. Make sure wallbash is set to "theme mode"
3. Open Dolphin
4. Open any drop down menu in Dolphin

### Expected Behavior

It should have a non glitched shadow and not lag my computer (imagine the drop down doesn't have the auto colors
![image](https://github.com/user-attachments/assets/e14040d7-31b1-4835-8453-92cf37a9e043)

### Actual Behavior

It has a glitched shadow and lags my computer when moving the cursor over it
![image](https://github.com/user-attachments/assets/b24432f6-057b-4359-8473-f80346228d70)

### Environment
- Linux Distro: Endeavour OS
- Linux Version, output of `uname -a`: `Linux hp-endeavour 6.6.42-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 25 Jul 2024 08:14:54 +0000 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`: `v0.41.2`
- Installation Environment: Main Hardware
- Other info: 
   - Resolution: `1366x768@60.05900`

### Additional Information

The only modified file is the config.ctl file for waybar. It shouldn't affect Dolphin.

**Comment by kRHYME7** [comment] 2024-07-31 05:16
@TheKamboy  What happens when you enable in wallbash mode. (Be sure to open a new instance of dolphin 

![image](https://github.com/user-attachments/assets/03594050-9d1b-4e2c-bdfe-b68785e17d6a)

**Comment by TheKamboy** [comment] 2024-07-31 05:48
> @TheKamboy  What happens when you enable in wallbash mode. (Be sure to open a new instance of dolphin 
> 
> ![image](https://github.com/user-attachments/assets/03594050-9d1b-4e2c-bdfe-b68785e17d6a)
> 

I already mentioned that auto mode is not affected, it's theme mode.

**Comment by rishav12s** [comment] 2024-08-01 14:42
found the solution

the fix is to get the updated kvantum theme files from the github repos of both the themes 

should i open a pr for it in hyde-themes but the problem is the prasanth is inactive and no body is accepting prs on that repo

**Comment by kRHYME7** [comment] 2024-08-01 15:43
> fix is to get the updated kvantum theme files from

if only the theme files then `Hyde theme patch ` will just update it.

**Comment by rishav12s** [comment] 2024-08-01 16:25
nah like you have to download the files from the kvantum theme repo of the orginal creators and then rename the files to .theme (they recently updated them to fix dolphin's lag)

not from  the HyDE theme repos

**Comment by TheKamboy** [comment] 2024-08-01 16:38
> nah like you have to download the files from the kvantum theme repo of the orginal creators and then rename the files to .theme (they recently updated them to fix dolphin's lag)
> 
> not from  the HyDE theme repos 

Can you send the repo with the kvantum files?

**Comment by rishav12s** [comment] 2024-08-01 17:08
Dracula : https://github.com/dracula/gtk/tree/master/kde/kvantum/Dracula-purple

Nordic Blue :
https://github.com/EliverLara/Nordic/tree/master/kde/kvantum/Nordic-bluish

**Comment by TheKamboy** [comment] 2024-08-02 00:28
> Dracula : https://github.com/dracula/gtk/tree/master/kde/kvantum/Dracula-purple
> 
> Nordic Blue : https://github.com/EliverLara/Nordic/tree/master/kde/kvantum/Nordic-bluish

Did not fix the issue with Dracula.

**Comment by TheKamboy** [comment] 2024-08-02 00:30
> > Dracula : https://github.com/dracula/gtk/tree/master/kde/kvantum/Dracula-purple
> > Nordic Blue : https://github.com/EliverLara/Nordic/tree/master/kde/kvantum/Nordic-bluish
> 
> Did not fix the issue with Dracula.

Nevermind, they didn't push it to master lol

**Comment by TheKamboy** [comment] 2024-08-02 00:34
Ok, some things now look old school (drop downs makes me think of windows vista) but I can now close this issue as it seems it's fixed for me, they are going to fix other themes, everything is now good.

**Comment by rishav12s** [comment] 2024-08-02 08:14
@TheKamboy bro could you keep this open as it has not been fixed in the HyDE repos 

keeping it open will help the owner and devs to fix the issue officially later

**Comment by kRHYME7** [comment] 2024-08-02 09:26
we can close it here, and link this issue to the themes repo.. Also I think you can have MR to the respective theme repos.

**Comment by TheKamboy** [comment] 2024-08-02 21:30
I guess I'll reopen it

**Comment by iamtheabdi** [comment] 2024-08-03 05:35
Also, it doesn't just affect Dolphin, i first encountered this bug with Kate.

**Comment by TheKamboy** [comment] 2024-08-03 05:39
> Also, it doesn't just affect Dolphin, i first encountered this bug with Kate.

Updated the title to reflect that

**Comment by rishav12s** [comment] 2024-08-03 06:49
yeah due to kvantum svg being outdated 

that is what causing this

**Comment by abenezerw** [comment] 2024-08-15 05:24
> yeah due to kvantum svg being outdated
> 
> that is what causing this

can you tell me which files you changed specifically? i couldnt find the files named .kvconfig on my system in dracula

**Comment by abenezerw** [comment] 2024-08-15 05:43
> > yeah due to kvantum svg being outdated
> > that is what causing this
> 
> can you tell me which files you changed specifically? i couldnt find the files named .kvconfig on my system in dracula

nevermind solved by changing the wallbash.svg to wallbash.theme in .config/Kvantum/wallbash/

**Comment by abenezerw** [comment] 2024-09-17 15:14
This was fixed on latest version of Hyde. Would you mind closing the issue if it’s been solved for you as well. 
@TheKamboy

**Closed** 2024-09-17 16:57 UTC
Labels: bug
