### ISSUE TITLE
[Bug]: dolphin background won't follow the theme

### ISSUE THREAD

**Issue by Raze4284** [prasanthrangan/hyprdots#1843] opened 2024-09-14 14:36 UTC
After fresh installing endeavourOS i installed hyprdots and seems like my dolphin got problems
Idk why it white, i patched themes
![image](https://github.com/user-attachments/assets/e9571ece-9ff7-469c-9d55-cd774978d0a4)

**Comment by kRHYME7** [comment] 2024-09-14 15:21
Let's just wait (few months) for official documentation from KDe. They love breaking changes lol.

**Comment by Raze4284** [comment] 2024-09-14 15:23
> Let's just wait (few months) for official documentation from KDe. They love breaking changes lol.
Thank you.. Its hopeful :_)

**Comment by Raze4284** [comment] 2024-09-14 15:25
> Let's just wait (few months) for official documentation from KDe. They love breaking changes lol.

Btw what i can do now?

**Comment by kRHYME7** [comment] 2024-09-14 16:55
I'm using thunar or nemo as of the moment, as long as you don't have extra usecase for dolphin.

**Comment by openwick** [comment] 2024-09-15 12:36
I have KDE installed alongside hyprland and going into kde and setting global theme to dark makes dolphin look normal. Dont know why but u can use it for now I guess

**Comment by kRHYME7** [comment] 2024-09-15 12:45
> I have KDE installed alongside hyprland and going into kde and setting global theme to dark makes dolphin look normal. Dont know why but u can use it for now I guess


Can you share some "suspicious"  files where might kde write the color state for dolphin?  I only knew the icons are in kdeglobals.

**Comment by openwick** [comment] 2024-09-16 11:10
> Can you share some "suspicious" files where might kde write the color state for dolphin? I only knew the icons are in kdeglobals.

I don't know what files KDE is overwriting. Never themed KDE properly. Maybe some thing in /usr/share/plasma/desktoptheme/ ?

**Comment by Melk0rr** [comment] 2024-09-21 15:42
Hello, having the same issue.
As a temporary fix that worked for me:
According to [arch wiki](https://wiki.archlinux.org/title/Dolphin#Mismatched_folder_view_background_colors)

So i just added a dcol file to run the following
```bash
bgColor=$(grep "window.color=" "$HOME/.config/Kvantum/wallbash/wallbash.kvconfig" | awk -F '=' '{print $2}')
sed -i "/^BackgroundNormal=/c\BackgroundNormal=${bgColor}" "$HOME/.config/kdeglobals"
```

**Comment by kRHYME7** [comment] 2024-09-21 17:43
@Melk0rr  Hmm is Dolphin kde moving their configs to Kdeglobals now?.

**Comment by Melk0rr** [comment] 2024-09-21 18:01
Found a [kdeglobals exemple](https://github.com/totte/configurations/blob/master/.kde4/share/config/kdeglobals.example).

**Comment by elronat** [comment] 2024-09-26 13:14
got the same problem just with thunar. I just updated hyde and encountered this bug.
![240926_15h12m47s_screenshot](https://github.com/user-attachments/assets/87352568-4c40-4062-b15e-fdd3877014bb)

**Comment by kRHYME7** [comment] 2024-10-10 01:23
Hi everyone, 

Can you check if this env vars can potentially resolve the issue of dolphin?
![image](https://github.com/user-attachments/assets/2c5b5ed1-fb14-44d5-9124-7e0730e613c5)

**Comment by kRHYME7** [comment] 2024-10-10 02:27
reference here https://github.com/prasanthrangan/hyprdots/issues/1778

**Comment by ArctynFox** [comment] 2024-10-10 02:29
In response to https://github.com/prasanthrangan/hyprdots/issues/1778#issuecomment-2403791889
My wallbash is set to auto:
![image](https://github.com/user-attachments/assets/06a3a769-00a0-4c6a-b4fd-829d2279b99c)

**Comment by kRHYME7** [comment] 2024-10-10 02:39
@thyeun 

> Explain further, during fresh installation, the dolphin version is old version, and once it been install, it will cache in the setting, and if the cache setting are not clear out after the new version been install, when qt env change to kdeglobals.
>
>old version is using qt env
new version is using kdeglobals


How can I potentially clear it out?

**Comment by thyeun** [comment] 2024-10-10 03:19
You have to restart the plasma-dolphin service daemon to clear it, but i'm not sure latest upgrade still using that daemon or not.

**Comment by kRHYME7** [comment] 2024-10-10 03:51
It's not running on my end and I also can't enable it

**Comment by thyeun** [comment] 2024-10-10 13:53
Dolphin got a new update ```2.08.2-1```

The service sound like no more working.

**Comment by kRHYME7** [comment] 2024-10-10 15:36
> Dolphin got a new update 2.08.2-1
 
 
 And  resizing on dolphin excibits some stutter specially if the background is transparent.

**Comment by Melk0rr** [comment] 2024-10-17 09:25
Since last update I have yet another appearance:
![screenshot_20241017_11h23m17s](https://github.com/user-attachments/assets/83708ef2-01f2-46f5-bc7c-c61604cbaea8)

Top bar and view background colors are ignoring qt5ct, qt6ct, kvantum and even kdeglobals

**Comment by chrollorifat** [comment] 2024-10-20 06:26
At this point, what do we even do?

**Comment by kRHYME7** [comment] 2024-10-20 09:15
I can't really repro those issues as my dolphin is working fine. Maybe wait for dolphin to settle down it's breaking changes.

**Comment by SushiByte-beep** [comment] 2024-11-02 14:00
I found that by playing around with the KDE system themes that i can toggle dolphin between 2 modes. Interesting to note that editing the KDE themes does not actually affect the applied theme much further.

Either everything looks normal theming wise but i suffer many glitches and flickering

Or Performance is top notch and the background is washed out white like in picture of OP.

**Comment by kRHYME7** [comment] 2024-11-02 14:59
> i can toggle dolphin between 2 modes

I'm intrigued by this. How to do it. Is it in the Plasma GUI?

**Comment by SushiByte-beep** [comment] 2024-11-02 15:40
> I'm intrigued by this. How to do it. Is it in the Plasma GUI?

I have kde plasma installed and run kde system settings from within hyprdots. Then i go to themes. 

Global theme seems to have no effect, icon style works like normal.

Application style is what appears to toggle between the 2 variations. The default "breeze" and the Ms windows theme have the stable performance with white background.

All other application styles i tried have the correct dark background at the expense of stability.

**Comment by kRHYME7** [comment] 2024-11-02 15:53
> Application style is what appears to toggle between the 2 variations. The default KDE "breeze" and the Ms windows theme have the stable performance with white background.

I will try to look into this one. I assume variations means like themes right? 

I really want to try to replicate OPs issue but dolphin works perfectly on my end.

**Comment by SushiByte-beep** [comment] 2024-11-02 16:22
>  I assume variations means like themes right?

The theme applied remains to be the one i chose from Hyde actually. The only things changing are the background. some very minor gui details (like the status bar i have enabled)  and the performance. 

The default breeze theme and the MS windows theme appear identical to each-other, any edits i save separately also appear identical. I have found no explanation as to what it that causes the difference. 

Is it possible that different application styles in KDE uses different methods to save their paramters? It was my understanding they recently switched to storing some settings in kdeglobals. But maybe that is not enforced on older and custom themes?

**Comment by kRHYME7** [comment] 2024-11-03 02:50
> Is it possible that different application styles in KDE uses different methods 

yup kde has couple of ways in there theming which is too confusing to know which is which. 

But I would love to know what file is  change. Is it only the `kedglobals` ? If so it's dumb if only dolphin relies on that file. 
Can you also check if  dolphinrc can be use to  theme?  


![image](https://github.com/user-attachments/assets/a9fd53dd-9c75-4b9f-bafa-e7d12d3d2272)

**Comment by kRHYME7** [comment] 2024-11-03 03:01
Okay! I can confirm that we can use dolphinrc to handle Icons. But I would still prefer to use kdeglobals to handle the default terminal and icons. 

Moving forward, I think we can use dolphinrc to handle dolphin colors. I hate touching the kdeglobals (as well as dolphinrc) but if this is used to theme dolphin without touching kdeglobals then we have no other choice.  Konsole terminal also can be themed in konsolerc. 


Now I'm wondering if these *rc files can handle includes like the ones in `~/.gtkrc-2.0` file
So we can just make a separate file specific for hyDE without touching any user spsecific files e.g dolphinrc and kdeglobals.
![image](https://github.com/user-attachments/assets/26bada68-446c-4228-b508-eb577b131d89)

**Comment by fr0st-iwnl** [comment] 2024-11-10 06:36
I had the same problem, and what worked for me was downgrading **Dolphin** to an older version. Just install the '`downgrade`' tool (`sudo pacman -S downgrade`), then run `sudo downgrade dolphin` and try a few of the older versions. It’s a weird issue, but this did the trick for me!

**Comment by chrollorifat** [comment] 2024-11-10 08:38
kde has made dolphin too much depended on the other kde modules and stuff which makes it really hard to work with dolphin on DEs/WMs other than KDE's own ecosystem.

**Comment by Melk0rr** [comment] 2024-11-10 08:50
Downgrading a package should always ne something temporary. It is not a good practice. 
Actually, dolphin looks as expected now on m'y end.
What I did was :
- uninstall dolphin and every KDE app with the exception of kwallet and kvantum.
- using plocate I deleted every config files related to KDE or dolphin
- deleted temp files
- rebooted
- reinstaller dolphin
Dolphin also received a new update recently si maybe that helped too

**Comment by thyeun** [comment] 2024-11-10 09:51
@Melk0rr clear cache and everything reload/reinstall back, some how are not workable for certain user here, as per mentioned here.

@chrollorifat KDE always have a different way of doing things, some years ago, they using QT and some years now they using KDEglobals, and maybe some year later, they ignore both.  :))

**Comment by kRHYME7** [comment] 2024-11-10 10:05
>  using KDEglobals, and maybe some year later, they ignore both. :))
 
 We can also use dolphinrc to isolate the colors for dolphin only. Works for background but how about the dark text even on dark mode?  You got some idea in there?

**Comment by thyeun** [comment] 2024-11-10 10:14
The text previously control by kvantum but after the recent few times of update, it look like not that case any more. 

Really need someone from KDE side to explain, what been remain, and what been remove. 

We look like ```try and error``` here (very pity to you @kRHYME7 )

**Comment by chrollorifat** [comment] 2024-11-10 12:28
btw, a bit off topic from this issue, but are we going to implement hydegallery or hyprpanel in the future? or are we totally abandoning even the notion of it?

**Comment by kRHYME7** [comment] 2024-11-10 12:52
> btw, a bit off topic from this issue, but are we going to implement hydegallery or hyprpanel in the future? or are we totally abandoning even the notion of it?

https://github.com/HyDE-Project/hyde-gallery ? 
https://github.com/HyDE-Project/HyprPanel ? 


WDYM?

**Comment by thyeun** [comment] 2024-11-10 13:36
Both also i pass :)) that panel ugly, if compare with ```ags``` .

**Comment by kRHYME7** [comment] 2024-11-10 13:41
> compare with ags .

hyprpanel is implemted using ags.

**Comment by thyeun** [comment] 2024-11-10 13:55
i already pass ```ags```, that why i pass also.

**Comment by kRHYME7** [comment] 2024-11-12 00:59
@ Hello anyone here still got the Background  issue?  can you try to add this to your  `~/.config/dolphinrc` first then restart dolphin. Check if the background changes. 
```  
 [Colors:View]
BackgroundNormal=#ff00ff
```


If not try it in `~/.config/kdeglobals `

**Comment by SushiByte-beep** [comment] 2024-11-12 10:32
> @ Hello anyone here still got the Background issue? can you try to add this to your `~/.config/dolphinrc` (remove it first in the kdeglobals) first then restart dolphin. Check if the background changes.
> If not try it in `~/.config/kdeglobals `

I have tried both and neither file seems to have any effect. 
I have also tried copying your kdeglobals above entirely, also to no effect.

**Comment by kRHYME7** [comment] 2024-11-12 13:26
@SushiByte-beep  Can you show us some screenshots with dolphin on light theme (Material Sakura) and dark (Catppuccin Mocha)

**Comment by SushiByte-beep** [comment] 2024-11-12 14:42
> @SushiByte-beep Can you show us some screenshots with dolphin on light theme (Material Sakura) and dark (Catppuccin Mocha)

Mocha, Sakura and Gruvbox. Changing modes (dark/light/auto/theme) made no different for dolphin. 

![dark](https://github.com/user-attachments/assets/9dde9099-bad4-46f4-8e40-facde8d70563)
![lighttt](https://github.com/user-attachments/assets/d3c218a0-3b0f-4896-9a41-5676f16aded0)
![grub](https://github.com/user-attachments/assets/052f5221-1518-4472-b239-748933d877f9)

**Comment by kRHYME7** [comment] 2024-11-12 17:03
uhm did you restart dolphin across the theme change?

**Comment by SushiByte-beep** [comment] 2024-11-12 17:57
> uhm did you restart dolphin across the theme change?

Every time.

I also made a  screenshot of how it looks with other KDE themes using kde system settings, which appears similarly glitched. 

With these (kvantum, kvantum-dark, q5tc, q6tc) i  have horrible flicker not seen in the screenshot rendering them unusable. but the background does apply correctly

![quantum](https://github.com/user-attachments/assets/088c737b-ba47-4b8e-8ec4-5294832bde19)


The screenshots in my previous comment are identicaal for the breeze, Fushion and Ms win theme.

**Comment by SushiByte-beep** [comment] 2024-11-12 18:55
OK so i removed dolphin and plasma completely in order to reinstall them and learned some things. 

The first thing i noticed upon installing just dolphin is that by default, it is like the screenshot in my latest comment where the background mostly works but the font and list view are broken. The flicker appears to be gone.

When i install plasma, its breeze theme takes over and the background changes to white for all themes. From that point the behaviour is a toggle between 2 modes as explained above.

I suppose the fix for this issue is if you install KDE plasma together with hyprland, you have to change the application theme back.  But as for now this bug also acts for as a temporary workaround to the font and list view not working.

**Comment by kRHYME7** [comment] 2024-11-13 00:59
For cases like this it's better to find out which themes dolphin. Can you check kdeglobals if the file changes when switching modes?

**Comment by SushiByte-beep** [comment] 2024-11-13 14:44
It seems for all themes its both kdglobals and dolphinrc but only for some settings.

What i did was remove both file contents before restarting dolphin with each time. 

kdeglobls only appears to save what icon pack is selected (in kde system settings) and the theme that is selected.

```
[Icons]
Theme=Gruvbox-Plus-Dark

[KDE]
widgetStyle=qt6ct-style
```

Dolphinrc always go back to this

```
[General]
Version=202
ViewPropsTimestamp=2024,11,13,15,37,47.626

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=22

[MainWindow]
ToolBarsMovable=Disabled

[MainWindow][Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly

```

I assume there must be yet another file that does store the colour values, i will keep looking but i am at a loss for where.

**Comment by kRHYME7** [comment] 2024-11-14 01:07
You can try in .local/state and in .local/share.

Also while trying to learn some kde6 themes I also found out plasmarc so maybe try to check it too

**Comment by kRHYME7** [comment] 2024-11-14 17:07
Anyone  can check if #1999 fixes this issue too?

**Comment by SushiByte-beep** [comment] 2024-11-15 06:54
ok so on my end the problem is threefold and i think i now know the fix for all.

Problem 1) White background appears to be caused by new theming features of KDE plasma. 
Fix: Change the application theme in KDE system settings to kvantum or remove  plasma-dekstop

Problem 2) Dolphin experiencing heavy stutter and glitching 
Fix: Make sure tooltip_delay=-1 is set in ~/.config/Kvantum/wallbash/wallbash.kvconfig

Problem 3) Transparent Font and list view color mismatch
Fix: [UiSettings] ColorScheme=* is set in ~/.config/dolphinrc

**Comment by kRHYME7** [comment] 2024-11-15 07:11
> Problem 1) White background appears to be caused by new theming features of KDE plasma.
Fix: Change the application theme in KDE system settings to kvantum or remove plasma-dekstop

Can you point out which file has this? if you can't find the file maybe share these plasmarc , kdeglobals, dolphinrc.

> Problem 2) Dolphin experiencing heavy stutter and glitching
Fix: Make sure tooltip_delay=-1 is set in ~/.config/Kvantum/wallbash/wallbash.kvconfig


This one also, so we should explicitly add this per theme? how about removing this config?


> Problem 3) Transparent Font and list view color mismatch
Fix: [UiSettings] ColorScheme=* is set in ~/.config/dolphinrc

This is actually a workaround  for a bug I guess because the issue appears when that section and variable is blank or unset. Maybe we don't need it soon or it might be documented.



Thank you for your help 🙏

**Comment by kRHYME7** [comment] 2024-11-24 14:41
Anyone having these issues can confirm https://github.com/prasanthrangan/hyprdots/issues/1908#issuecomment-2495985470 ?

**Comment by kRHYME7** [comment] 2024-11-25 05:13
Please do a PR so we can finally close this.

**Closed** 2024-11-25 12:37 UTC
Labels: bug

**Comment by kRHYME7** [comment] 2024-11-25 15:11
>  (after deleting them first) didnt yield such random results (at some point i had themes working while both kdeglobals and kcdolphin appeared empty)


Yup they should work because their states were saved in ~/.local/state/* . Some of your Gui changes will be saved in the state not in the  config.
So when debugging I removed both in config and in ./.local/state

**Comment by ArctynFox** [comment] 2024-11-25 22:22
Can also confirm that it fixes the background color for me. However, I still have UI border lines where there shouldn't be:
![image](https://github.com/user-attachments/assets/d7cc8352-abbd-48ba-928c-d95ae08fc013)

Is there a known fix for this, or is this something that might also need a separate issue thread?

**Comment by kRHYME7** [comment] 2024-11-26 01:20
You configured it that way.

can you share your dolphinrc and kdeglobals? I would like to have that borders

**Comment by ArctynFox** [comment] 2024-11-26 03:49
I have *not* configured it separately. As I have posted on multiple issue threads already, this is exactly how it looks for me on a new user, fresh install, etc after I install hyprdots via Hyde.

My dolphinrc is:
```
MenuBar=Disabled

[$Version]
update_info=dolphin_detailsmodesettings.upd:rename-leading-padding

[General]
ShowSelectionToggle=false
ShowStatusBar=false
Version=202
ViewPropsTimestamp=2023,4,26,16,58,48.324

[IconsMode]
MaximumTextLines=1
PreviewSize=112

[InformationPanel]
dateFormat=ShortFormat

[KFileDialog Settings]
Places Icons Auto-resize=false
Places Icons Static Size=16

[KPropertiesDialog]
2560x1080 screen: Window-Maximized=true

[MainWindow]
MenuBar=Disabled
ToolBarsMovable=Disabled

[MainWindow][Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly

[PlacesPanel]
IconSize=16

[PreviewSettings]
Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,ffmpegthumbs

[Toolbar mainToolBar]
IconSize=16
ToolButtonStyle=IconOnly
```

And kdeglobals is:
```
[General]
TerminalApplication=kitty

[Icons]
Theme=Tela-circle-dracula

[Colors:View]
BackgroundNormal=#00000000

[UiSettings]
ColorScheme=*
```

They are exactly what were pulled from the hyprdots repo when I pulled the update made to fix the background just earlier today, save for the automatic editing of kdeglobals performed by scripts bound in the Hyprland config.

**Comment by kRHYME7** [comment] 2024-11-26 06:02
remove any kde and dolphin related stuff in the ~/.local/state/*

once you have and launch dolphin the dolphinrc in the .config is almost useless  and the state might override.

**Comment by ArctynFox** [comment] 2024-11-26 06:36
Seems that doing this has not fixed the issue. All it did was move around my panel configuration...

**Comment by chrollorifat** [comment] 2024-11-26 13:56
> I have _not_ configured it that way. As I have posted on multiple issue threads already, this is exactly how it looks for me on a new user, fresh install, etc after I install hyprdots via Hyde.
> 
> My dolphinrc is:
> 
> ```
> MenuBar=Disabled
> 
> [$Version]
> update_info=dolphin_detailsmodesettings.upd:rename-leading-padding
> 
> [General]
> ShowSelectionToggle=false
> ShowStatusBar=false
> Version=202
> ViewPropsTimestamp=2023,4,26,16,58,48.324
> 
> [IconsMode]
> MaximumTextLines=1
> PreviewSize=112
> 
> [InformationPanel]
> dateFormat=ShortFormat
> 
> [KFileDialog Settings]
> Places Icons Auto-resize=false
> Places Icons Static Size=16
> 
> [KPropertiesDialog]
> 2560x1080 screen: Window-Maximized=true
> 
> [MainWindow]
> MenuBar=Disabled
> ToolBarsMovable=Disabled
> 
> [MainWindow][Toolbar mainToolBar]
> IconSize=16
> ToolButtonStyle=IconOnly
> 
> [PlacesPanel]
> IconSize=16
> 
> [PreviewSettings]
> Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,ffmpegthumbs
> 
> [Toolbar mainToolBar]
> IconSize=16
> ToolButtonStyle=IconOnly
> ```
> 
> And kdeglobals is:
> 
> ```
> [General]
> TerminalApplication=kitty
> 
> [Icons]
> Theme=Tela-circle-dracula
> 
> [Colors:View]
> BackgroundNormal=#00000000
> 
> [UiSettings]
> ColorScheme=*
> ```
> 
> They are exactly what were pulled from the hyprdots repo when I pulled the update made to fix the background just earlier today, save for the automatic editing of kdeglobals performed by scripts bound in the Hyprland config.

same issue for me here

**Comment by Dufour-Matisse** [comment] 2024-11-28 13:09
> ok so on my end the problem is threefold and i think i now know the fix for all.
> 
> Problem 1) White background appears to be caused by new theming features of KDE plasma. Fix: Change the application theme in KDE system settings to kvantum or remove plasma-dekstop
> 
> Problem 2) Dolphin experiencing heavy stutter and glitching Fix: Make sure tooltip_delay=-1 is set in ~/.config/Kvantum/wallbash/wallbash.kvconfig
> 
> Problem 3) Transparent Font and list view color mismatch Fix: [UiSettings] ColorScheme=* is set in ~/.config/dolphinrc

Had a pretty similar issue with file's name the same color as the background, and I was unable to change it (qt5-6 or Kvantum).

Used the 3rd fix and file name color came back to normal

Joined a pic of the issue I had:
![image](https://github.com/user-attachments/assets/009cb39e-d397-4f81-9230-55d650fce9cd)

**Comment by kRHYME7** [comment] 2024-11-28 16:42
For everyone following this issue.

Update your kdeglobals.
https://github.com/hyde-project/hyde/blob/master/Configs%2F.config%2Fkdeglobals#L1-L11


Add it in kdeglobals instead of dolphin, so the ark manager will be fixed also.

**Comment by Saifullah-Balghari** [comment] 2024-12-22 11:39
This worked for me.

1. Uninstall dolphin

2. delete everything related to dolphin from here:
~/.config
~/.local/share/
~/.local/state

3. create a kdeglogbals file and add these lines:
     [Colors:View]
    BackgroundNormal=#00000000
    
    [General]
    TerminalApplication=kitty
    
    [UiSettings]
    ColorScheme=*

4. reinstall dolphin.

**Comment by zarocknc** [comment] 2025-02-15 15:52
> I have _not_ configured it that way. As I have posted on multiple issue threads already, this is exactly how it looks for me on a new user, fresh install, etc after I install hyprdots via Hyde.
> 
> My dolphinrc is:
> 
> ```
> MenuBar=Disabled
> 
> [$Version]
> update_info=dolphin_detailsmodesettings.upd:rename-leading-padding
> 
> [General]
> ShowSelectionToggle=false
> ShowStatusBar=false
> Version=202
> ViewPropsTimestamp=2023,4,26,16,58,48.324
> 
> [IconsMode]
> MaximumTextLines=1
> PreviewSize=112
> 
> [InformationPanel]
> dateFormat=ShortFormat
> 
> [KFileDialog Settings]
> Places Icons Auto-resize=false
> Places Icons Static Size=16
> 
> [KPropertiesDialog]
> 2560x1080 screen: Window-Maximized=true
> 
> [MainWindow]
> MenuBar=Disabled
> ToolBarsMovable=Disabled
> 
> [MainWindow][Toolbar mainToolBar]
> IconSize=16
> ToolButtonStyle=IconOnly
> 
> [PlacesPanel]
> IconSize=16
> 
> [PreviewSettings]
> Plugins=appimagethumbnail,audiothumbnail,comicbookthumbnail,cursorthumbnail,djvuthumbnail,ebookthumbnail,exrthumbnail,imagethumbnail,jpegthumbnail,kraorathumbnail,windowsexethumbnail,windowsimagethumbnail,opendocumentthumbnail,svgthumbnail,ffmpegthumbs
> 
> [Toolbar mainToolBar]
> IconSize=16
> ToolButtonStyle=IconOnly
> ```
> 
> And kdeglobals is:
> 
> ```
> [General]
> TerminalApplication=kitty
> 
> [Icons]
> Theme=Tela-circle-dracula
> 
> [Colors:View]
> BackgroundNormal=#00000000
> 
> [UiSettings]
> ColorScheme=*
> ```
> 
> They are exactly what were pulled from the hyprdots repo when I pulled the update made to fix the background just earlier today, save for the automatic editing of kdeglobals performed by scripts bound in the Hyprland config.

Thank you this worked to change my icons in dolphin 24.12.2

**Comment by kRHYME7** [comment] 2025-02-18 02:12
```kdeglobals

[UiSettings]
ColorScheme=color
```


This is the correct way to set it in HyDE .

**Comment by daniel-theia** [comment] 2025-12-30 18:36
Putting the following in `~/.config/kdeglobals`:

> ```
> [Colors:View]
> BackgroundNormal=#00000000
> ```

This specifically fixes KDE apps (i.e. Konqueror) not correctly reading the Ubuntu dark theme and displaying white text on white background.
