### ISSUE TITLE
[Feature Request]: Short description of the feature

### ISSUE THREAD

**Issue by Sveen** [prasanthrangan/hyprdots#1222] opened 2024-03-31 07:34 UTC
### Description

make the colorscheme of neovim automatically match the colorscheme of kitty

**Comment by Enigma1309** [comment] 2024-03-31 12:55
self dupe of issue #1225

**Comment by dieBakterie** [comment] 2024-04-04 22:47
Could this issue been closed it's an duplicate

**Closed** 2024-04-05 02:09 UTC
Labels: enhancement
