### ISSUE TITLE
please fix the automatic logout issue

### ISSUE THREAD

**Issue by Yougraj** [prasanthrangan/hyprdots#13] opened 2023-06-06 15:04 UTC

**Comment by akashgagda** [comment] 2023-06-06 15:39
Can you provide more information? Because there no logout issue for me

**Comment by akashgagda** [comment] 2023-06-06 15:40
> 

Can you provide more information? Because there no logout issue for me

**Comment by prasanthrangan** [comment] 2023-06-06 16:37
what the issue? I've no problem with logout

**Comment by Yougraj** [comment] 2023-06-06 16:47
It suddenly logout from hyprland session i don't understand what is happening

**Comment by prasanthrangan** [comment] 2023-06-07 05:59
> suddenly logout from hyprland running session i don't understand what is happening did I do something wrong or i didn't install something

Does it take you back to TTY or the sddm screen? Are you using nvidia card?
Also, can you check the hyprland log file? here is the wiki to check logs -
https://wiki.hyprland.org/Crashes-and-Bugs/

**Comment by 220320bs** [comment] 2023-06-07 05:59
> 突然从 hyprland 运行会话注销 我不明白发生了什么事 我做错了什么或者我没有安装什么东西

**Comment by 220320bs** [comment] 2023-06-07 06:00
@Yougraj  I have also encountered, but the back is gone

**Comment by Yougraj** [comment] 2023-06-07 06:06
> @220320bs when i working on krita this is happening idonot know if krita(flatpak) is the issue

**Comment by Yougraj** [comment] 2023-06-07 06:07
> > suddenly logout from hyprland running session i don't understand what is happening did I do something wrong or i didn't install something
> 
> Does it take you back to TTY or the sddm screen? Are you using nvidia card? Also, can you check the hyprland log file? here is the wiki to check logs - https://wiki.hyprland.org/Crashes-and-Bugs/

i am not using nvidia card

**Comment by 220320bs** [comment] 2023-06-07 06:13
@Yougraj I use amd card

**Comment by prasanthrangan** [comment] 2023-06-07 13:08
if you are not using NVIDIA, you could try commenting out these variables from hyprland.conf -

```
#env = GBM_BACKEND,nvidia-drm
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_DRM_NO_ATOMIC,1
```

**Comment by Yougraj** [comment] 2023-06-08 04:59
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Sorry, didn't mean to...

Hyprland received signal 6 (Aborted)

Version: df98db50924c05f0bd7a8c95cdab5d4ece13a1f1

System info:
	System name: Linux
	Node name: arch
	Release: 6.3.5-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Tue, 30 May 2023 13:44:01 +0000

GPU:
	0000:00:02.0 VGA compatible controller [0300]: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] [8086:9a49] (rev 01) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x78e) [0x555dcd86e5de]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x555dcd809e3c]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x39ab0) [0x7fbfcd44fab0]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x8926c) [0x7fbfcd49f26c]
		??
		??:0
	#4 | /usr/lib/libc.so.6(gsignal+0x18) [0x7fbfcd44fa08]
		??
		??:0
	#5 | /usr/lib/libc.so.6(abort+0xd7) [0x7fbfcd438538]
		??
		??:0
	#6 | /usr/lib/libc.so.6(+0x2245c) [0x7fbfcd43845c]
		??
		??:0
	#7 | /usr/lib/libc.so.6(+0x323d6) [0x7fbfcd4483d6]
		??
		??:0
	#8 | /usr/lib/libwlroots.so.12032(+0x3b6dc) [0x7fbfce0c96dc]
		??
		??:0
	#9 | /usr/lib/libwlroots.so.12032(wlr_render_texture_with_matrix+0x48) [0x7fbfce0c9728]
		??
		??:0
	#10 | /usr/lib/libwlroots.so.12032(wlr_output_render_software_cursors+0x2a3) [0x7fbfce0fc813]
		??
		??:0
	#11 | Hyprland(_ZN13CHyprRenderer13renderMonitorEP8CMonitor+0x5cc) [0x555dcd92e6cc]
		??
		??:0
	#12 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x3c) [0x555dcd8ab38c]
		??
		??:0
	#13 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7fbfce04501e]
		??
		??:0
	#14 | /usr/lib/libwlroots.so.12032(+0x56a58) [0x7fbfce0e4a58]
		??
		??:0
	#15 | /usr/lib/libdrm.so.2(drmHandleEvent+0xff) [0x7fbfce0149af]
		??
		??:0
	#16 | /usr/lib/libwlroots.so.12032(+0x592b9) [0x7fbfce0e72b9]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7fbfce046ae2]
		??
		??:0
	#18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7fbfce0472d7]
		??
		??:0
	#19 | Hyprland(main+0x4b4) [0x555dcd7fa9a4]
		??
		??:0
	#20 | /usr/lib/libc.so.6(+0x23850) [0x7fbfcd439850]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fbfcd43990a]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x555dcd809ce5]
		??
		??:0


Log tail:
[LOG] Callback 555dd0cfca80 -> 555dd0cfca78, XWayland Window removed.
[LOG] Callback 555dd0cfcc20 -> 555dd0cfcc18, XWayland Window removed.
[LOG] New XWayland Surface created (class (null)).
[LOG] Registered signal for owner 555dd0d2f230: 555dcfb9c740 -> 555dd0d2f980 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d2f230: 555dcfb9c750 -> 555dd0d2f9e8 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d2f230: 555dcfb9c6c0 -> 555dd0d2f368 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d2f230: 555dcfb9c800 -> 555dd0d2f918 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d2f230: 555dcfb9c6d0 -> 555dd0d2f778 (owner: XWayland Window)
[LOG] New XWayland Surface created (class (null)).
[LOG] Registered signal for owner 555dd0d30670: 555dd0cfe530 -> 555dd0d30dc0 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d30670: 555dd0cfe540 -> 555dd0d30e28 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d30670: 555dd0cfe4b0 -> 555dd0d307a8 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d30670: 555dd0cfe5f0 -> 555dd0d30d58 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d30670: 555dd0cfe4c0 -> 555dd0d30bb8 (owner: XWayland Window)
[LOG] New XWayland Surface created (class (null)).
[LOG] Registered signal for owner 555dd0d31db0: 555dd0d31cb0 -> 555dd0d32500 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d31db0: 555dd0d31cc0 -> 555dd0d32568 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d31db0: 555dd0d31c30 -> 555dd0d31ee8 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d31db0: 555dd0d31d70 -> 555dd0d32498 (owner: XWayland Window)
[LOG] Registered signal for owner 555dd0d31db0: 555dd0d31c40 -> 555dd0d322f8 (owner: XWayland Window)
[LOG] Window 555dd0d2f230 destroyed, queueing. (class )
[LOG] XWayland class raw: (null)
[LOG] Callback 555dd0d2f390 -> 555dd0d2f388, XWayland Window removed.
[LOG] Callback 555dd0d2f7a0 -> 555dd0d2f798, XWayland Window removed.
[LOG] Callback 555dd0d2f940 -> 555dd0d2f938, XWayland Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Callback 555dd0d2fa10 -> 555dd0d2fa08, XWayland Window removed.
[LOG] Callback 555dd0d2f9a8 -> 555dd0d2f9a0, XWayland Window removed.
[LOG] Unmapped window 555dd0d2f230 removed instantly
[LOG] Window 555dd0d30670 destroyed, queueing. (class )
[LOG] XWayland class raw: (null)
[LOG] Callback 555dd0d307d0 -> 555dd0d307c8, XWayland Window removed.
[LOG] Callback 555dd0d30be0 -> 555dd0d30bd8, XWayland Window removed.
[LOG] Callback 555dd0d30d80 -> 555dd0d30d78, XWayland Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Callback 555dd0d30e50 -> 555dd0d30e48, XWayland Window removed.
[LOG] Callback 555dd0d30de8 -> 555dd0d30de0, XWayland Window removed.
[LOG] Unmapped window 555dd0d30670 removed instantly
[LOG] Window 555dd0d31db0 destroyed, queueing. (class )
[LOG] XWayland class raw: (null)
[LOG] Callback 555dd0d31f10 -> 555dd0d31f08, XWayland Window removed.
[LOG] Callback 555dd0d32320 -> 555dd0d32318, XWayland Window removed.
[LOG] Callback 555dd0d324c0 -> 555dd0d324b8, XWayland Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Callback 555dd0d32590 -> 555dd0d32588, XWayland Window removed.
[LOG] Callback 555dd0d32528 -> 555dd0d32520, XWayland Window removed.
[LOG] Unmapped window 555dd0d31db0 removed instantly
[LOG] Callback 555dd0cfccf0 -> 555dd0cfcce8, XWayland Window removed.
[LOG] Callback 555dd0cfcc88 -> 555dd0cfcc80, XWayland Window removed.
[LOG] Cleanup: destroyed a window

**Comment by Yougraj** [comment] 2023-06-08 05:00
I am using this on my 2nd laptop and this is the crash report

**Comment by Yougraj** [comment] 2023-06-08 05:01
> if you are not using NVIDIA, you could try commenting out these variables from hyprland.conf -
> 
> ```
> #env = GBM_BACKEND,nvidia-drm
> env = LIBVA_DRIVER_NAME,nvidia
> env = __GLX_VENDOR_LIBRARY_NAME,nvidia
> env = __GL_VRR_ALLOWED,1
> env = WLR_NO_HARDWARE_CURSORS,1
> env = WLR_DRM_NO_ATOMIC,1
> ```
> 
> were you able to find any error messages from the log?

not working

**Comment by BenjaminLanger** [comment] 2023-06-08 12:51
Its probably this issue https://github.com/hyprwm/Hyprland/issues/2438. I also had the crashes but after building hyprland from source, with this fix implemented it hasn't happened since. I don't know 100% if it was the issue but you can try if it fixes it for you

**Comment by Yougraj** [comment] 2023-06-09 11:05
I will try

**Comment by Yougraj** [comment] 2023-06-09 13:58
> Its probably this issue [hyprwm/Hyprland#2438](https://github.com/hyprwm/Hyprland/issues/2438). I also had the crashes but after building hyprland from source, with this fix implemented it hasn't happened since. I don't know 100% if it was the issue but you can try if it fixes it for you

Issue is solve by making Hyprland from source thanks bro

**Comment by BenjaminLanger** [comment] 2023-06-14 09:15
It was an issue in Hyprland that was caused by a change in wlroots i think. This was the commit that fixed it https://github.com/hyprwm/Hyprland/commit/10db5a4fdbb0150af1165ea5591081c5182bb416. It was described in the issue I linked before.

**Comment by prasanthrangan** [comment] 2023-06-14 14:50
@BenjaminLanger , thank you!

Closing this issue...

**Closed by prasanthrangan** 2023-06-14 14:50 UTC
