### ISSUE TITLE
Waybar can't run

### ISSUE THREAD

**Issue by megurashi** [prasanthrangan/hyprdots#697] opened 2023-12-26 19:33 UTC
Just installed hyprdots for the first time, completed with no errors and all package was installed

for the waybar, it seems cant running, even after reinstall the script and reinstall arch, is there some package i miss?

`Selected theme: Rose-Pine`
`eDP-1: 1366x768, scale: 1, currently displaying: image: /home/fenrir/.config/swww/Decay-Green/moments_before_desk.png
ok`
`environment: line 5: /home/fenrir/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory`
`sed: can't read /home/fenrir/.config/spicetify/Themes/Sleek/Wall-Dcol.ini: No such file or directory`
`/home/fenrir/.config/hypr/scripts/wbarstylegen.sh: line 17: [: !=: unary operator expected`

if i just run waybar directly
`(waybar:16297): Gtk-WARNING **: 02:28:54.806: Theme parsing error: gtk.css:3213:16: Unit is missing.`
`[2023-12-27 02:28:54.856] [info] Using configuration file /home/fenrir/.config/waybar/config.jsonc`
`[2023-12-27 02:28:54.858] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop`
`[2023-12-27 02:28:54.858] [info] Using CSS file /home/fenrir/.config/waybar/style.css`
`[2023-12-27 02:28:54.859] [error] theme.css:1:7Expected a valid selector`

./wbarconfgen.sh
![image](https://github.com/prasanthrangan/hyprdots/assets/83998757/02e43c72-8d30-4ff6-80cf-caaca64c7e0c)

**Comment by tushargoyalofficial** [comment] 2023-12-28 17:58
@megurashi system info and what process you followd to install arch linux

**Comment by megurashi** [comment] 2023-12-29 04:42
@tushargoyalofficial my system is i5-5200U, NVIDIA GeForce 920M

on arch installed hyprland polkit version with sddm greeter, nvidia propietary, pipewire as audio

**Comment by kRHYME7** [comment] 2023-12-29 05:57
have you tried changing themes? or toggling wallbash?

**Comment by tushargoyalofficial** [comment] 2023-12-29 06:06
@megurashi can you give a try with Endeavour OS, no desktop install ?
https://www.youtube.com/watch?v=mb8h1-LB9K0
you can follow this video

**Comment by AsarNaufil** [comment] 2024-01-13 08:52
Hi @megurashi, I have experienced a similar bug before, in my case, the problem is that the `~/.config/waybar/style.css`  had invalid css, i.e. just the name of the file. Please check the file contents. If needed, you can paste my file:

```css
* {
    border: none;
    border-radius: 0px;
    font-family: "JetBrainsMono Nerd Font";
    font-weight: bold;
    font-size: 12px;
    min-height: 10px;
}

@import "themes/theme.css";

window#waybar {
    background: @bar-bg;
}

tooltip {
    background: @main-bg;
    color: @main-fg;
    border-radius: 8px;
    border-width: 0px;
}

#workspaces button {
    box-shadow: none;
	text-shadow: none;
    padding: 0px;
    border-radius: 9px;
    margin-top: 3px;
    margin-bottom: 3px;
    padding-left: 3px;
    padding-right: 3px;
    color: @main-fg;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.5s cubic-bezier(.55,-0.68,.48,1.682);
}

#workspaces button.active {
    background: @wb-act-bg;
    color: @wb-act-fg;
    margin-left: 3px;
    padding-left: 12px;
    padding-right: 12px;
    margin-right: 3px;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#workspaces button:hover {
    background: @wb-hvr-bg;
    color: @wb-hvr-fg;
    padding-left: 3px;
    padding-right: 3px;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#taskbar button {
    box-shadow: none;
	text-shadow: none;
    padding: 0px;
    border-radius: 9px;
    margin-top: 3px;
    margin-bottom: 3px;
    padding-left: 3px;
    padding-right: 3px;
    color: @wb-color;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.5s cubic-bezier(.55,-0.68,.48,1.682);
}

#taskbar button.active {
    background: @wb-act-bg;
    color: @wb-act-color;
    margin-left: 3px;
    padding-left: 12px;
    padding-right: 12px;
    margin-right: 3px;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#taskbar button:hover {
    background: @wb-hvr-bg;
    color: @wb-hvr-color;
    padding-left: 3px;
    padding-right: 3px;
    animation: gradient_f 20s ease-in infinite;
    transition: all 0.3s cubic-bezier(.55,-0.68,.48,1.682);
}

#backlight,
#battery,
#bluetooth,
#custom-cliphist,
#clock,
#cpu,
#custom-gpuinfo,
#idle_inhibitor,
#language,
#memory,
#custom-mode,
#mpris,
#network,
#custom-power,
#pulseaudio,
#custom-spotify,
#taskbar,
#tray,
#custom-updates,
#custom-wallchange,
#custom-wbar,
#window,
#workspaces,
#custom-l_end,
#custom-r_end,
#custom-sl_end,
#custom-sr_end,
#custom-rl_end,
#custom-rr_end {
    color: @main-fg;
    background: @main-bg;
    opacity: 1;
    margin: 4px 0px 4px 0px;
    padding-left: 4px;
    padding-right: 4px;
}

#workspaces,
#taskbar {
    padding: 0px;
}

#custom-r_end {
    border-radius: 0px 22px 22px 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-l_end {
    border-radius: 22px 0px 0px 22px;
    margin-left: 9px;
    padding-left: 3px;
}

#custom-sr_end {
    border-radius: 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-sl_end {
    border-radius: 0px;
    margin-left: 9px;
    padding-left: 3px;
}

#custom-rr_end {
    border-radius: 0px 8px 8px 0px;
    margin-right: 9px;
    padding-right: 3px;
}

#custom-rl_end {
    border-radius: 8px 0px 0px 8px;
    margin-left: 9px;
    padding-left: 3px;
}
```

**Comment by kRHYME7** [comment] 2024-01-13 09:41
> have you tried changing themes? or toggling wallbash?


have you tried changing themes? or toggling wallbash?

**Comment by changsijay** [comment] 2024-01-17 22:36
installed today, got similar issue here, always core dump
(if i run `waybar -c /dev/null` it didn't core dump and run well)

debug log below (tho seems not that helpful log)

```
❯ waybar -l debug
[2024-01-18 05:32:12.251] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config
[2024-01-18 05:32:12.251] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config.jsonc
[2024-01-18 05:32:12.251] [debug] Try expanding: $HOME/.config/waybar/config
[2024-01-18 05:32:12.251] [debug] Try expanding: $HOME/.config/waybar/config.jsonc
[2024-01-18 05:32:12.251] [debug] Found config file: $HOME/.config/waybar/config.jsonc
[2024-01-18 05:32:12.251] [info] Using configuration file /home/csj/.config/waybar/config.jsonc
[2024-01-18 05:32:12.252] [info] Discovered appearance 'dark'
[2024-01-18 05:32:12.252] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/style-dark.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/style.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $HOME/.config/waybar/style-dark.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $HOME/.config/waybar/style.css
[2024-01-18 05:32:12.252] [debug] Found config file: $HOME/.config/waybar/style.css
[2024-01-18 05:32:12.252] [info] Using CSS file /home/csj/.config/waybar/style.css
[2024-01-18 05:32:12.256] [debug] Output detection done: DP-3 (Dell Inc. DELL U2720Q JBF2V83)
[2024-01-18 05:32:12.260] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.260] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.261] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.261] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.262] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.262] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.262] [debug] Use custom icon theme: Tela-circle-dracula
[2024-01-18 05:32:12.262] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.262] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.263] [warning] module : Unknown module: 
[2024-01-18 05:32:12.263] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.263] [debug] Received SIGCHLD in signalThread
[1]    42641 segmentation fault (core dumped)  waybar -l debug
```

**Comment by changsijay** [comment] 2024-01-17 22:36
installed today, got similar issue here, always core dump
(if i run `waybar -c /dev/null` it didn't core dump and run well)

debug log below (tho seems not that helpful log)

```
❯ waybar -l debug
[2024-01-18 05:32:12.251] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config
[2024-01-18 05:32:12.251] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/config.jsonc
[2024-01-18 05:32:12.251] [debug] Try expanding: $HOME/.config/waybar/config
[2024-01-18 05:32:12.251] [debug] Try expanding: $HOME/.config/waybar/config.jsonc
[2024-01-18 05:32:12.251] [debug] Found config file: $HOME/.config/waybar/config.jsonc
[2024-01-18 05:32:12.251] [info] Using configuration file /home/csj/.config/waybar/config.jsonc
[2024-01-18 05:32:12.252] [info] Discovered appearance 'dark'
[2024-01-18 05:32:12.252] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/style-dark.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $XDG_CONFIG_HOME/waybar/style.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $HOME/.config/waybar/style-dark.css
[2024-01-18 05:32:12.252] [debug] Try expanding: $HOME/.config/waybar/style.css
[2024-01-18 05:32:12.252] [debug] Found config file: $HOME/.config/waybar/style.css
[2024-01-18 05:32:12.252] [info] Using CSS file /home/csj/.config/waybar/style.css
[2024-01-18 05:32:12.256] [debug] Output detection done: DP-3 (Dell Inc. DELL U2720Q JBF2V83)
[2024-01-18 05:32:12.260] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.260] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.261] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.261] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.262] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.262] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.262] [debug] Use custom icon theme: Tela-circle-dracula
[2024-01-18 05:32:12.262] [debug] Received SIGCHLD in signalThread
[2024-01-18 05:32:12.262] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.263] [warning] module : Unknown module: 
[2024-01-18 05:32:12.263] [debug] Cmd exited with code 0
[2024-01-18 05:32:12.263] [debug] Received SIGCHLD in signalThread
[1]    42641 segmentation fault (core dumped)  waybar -l debug
```

**Comment by kRHYME7** [comment] 2024-01-18 01:03
Have you tried toggling your waybar to the next layout?

**Comment by megurashi** [comment] 2024-01-25 08:12
> @megurashi can you give a try with Endeavour OS, no desktop install ? https://www.youtube.com/watch?v=mb8h1-LB9K0 you can follow this video

Now i'm using endeavour, everything works now

**Comment by kRHYME7** [comment] 2024-02-15 05:34
Nice! Closing this as resolved.

**Closed by kRHYME7** 2024-02-15 05:34 UTC
Labels: bug
