### ISSUE TITLE
[Bug]: Offset Icons

### ISSUE THREAD

**Issue by TurtleMeds** [prasanthrangan/hyprdots#865] opened 2024-02-12 19:18 UTC
### Description

Icons in Waybar and Rofi are offset to the right

### Steps to Reproduce

1. Open Rofi
2. Look at icons
OR
1. Look at icons in waybar

### Expected Behavior

Icons are centered in buttons

### Actual Behavior

They are offset to the right.

### Screenshots

![240212_11h11m51s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/76972146/ba51b47b-4905-496f-a006-5f9032a986fc)
![240212_11h12m19s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/76972146/72d3bbe2-6d21-4d52-a894-4cab54a5104c)

### Environment

- Linux Distro: Arch Linux
- Linux Version, output of `uname -a`: `Linux E16 6.7.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Feb 2024 22:07:49 +0000 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`: 
```
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

flags: (if any)
```
- Installation Environment: Real hardware
- Other info: Display Resolution 2560x1600 at scale 1.6

### Additional Information

I changed the font to another nerd font (Fira Code). Is that the issue?

**Comment by kRHYME7** [comment] 2024-02-13 02:16
@TurtleMeds Hello,👋
  This is a normal behavior and I can't find a configuration regarding centering the text.  Rofi is text-based and those Icons are just glyphs. and most of them aren't centered. 
  
  Also, this is a duplicate of #796, Let's use that thread instead, to de-clutter issues.  Thank you for understanding.

**Closed by kRHYME7** 2024-02-13 02:16 UTC
Labels: bug, duplicate
