### ISSUE TITLE
Login screen changed to sddm default.

### ISSUE THREAD

**Issue by Radrahil** [prasanthrangan/hyprdots#973] opened 2024-02-27 04:06 UTC
The login screen has changed to the sddm default. How do I fix this?

**Comment by SpaceLarry14** [comment] 2024-02-27 04:07
I can confirm the latest updates did the same thing to me

**Comment by kRHYME7** [comment] 2024-02-27 06:18
Dupe #972

**Comment by kRHYME7** [comment] 2024-02-27 13:17
You can monitor the fist raised issue #972,  as this is duplicate of #972. Re-open this if necessary.

**Closed by kRHYME7** 2024-02-27 13:17 UTC
