### ISSUE TITLE
[Bug]: Wallpaper not loading when i login after i logout

### ISSUE THREAD

**Issue by Sveen** [prasanthrangan/hyprdots#1180] opened 2024-03-25 10:37 UTC
![240325_12h34m38s_screenshot](https://github.com/prasanthrangan/hyprdots/assets/140259096/ebb3e8d2-ba5b-4f22-a6a7-5870e1d19ed9)
After i logout using the keybinding SUPER delete  and i sign in to my user account my wallpaper doesnt show

- Linux Distro: [ArchLinux]

**Comment by kRHYME7** [comment] 2024-03-25 11:03
maybe a dupe of the other issue. 

What is the output for ``` yay -Qs swww ``` ? 

what happens if you run   ``` swww kill``` ?  then change wallpaper ?

**Comment by dieBakterie** [comment] 2024-03-25 11:07
Should i Go with swww or with swww-git i want avoid this issue and it's kinda related it's the chaotic aur(paru) First time using Not yay so. Thanks for the Help in advance and of course for the great project's

**Comment by kRHYME7** [comment] 2024-03-25 11:11
>  chaotic aur (paru) 

Both are not related

+ paru is the same with yay

+ chaotic aur is a repository that stores pre built aur packages which makes installation faster

Therefore if you have chaotic AUR instalaltion of some "-git" package will be faster because it is "sometime" pre buil/compiled.

**Comment by dieBakterie** [comment] 2024-03-25 11:13
OK thanks for the info. Then i'll Go with the normal one i guess

**Comment by kRHYME7** [comment] 2024-03-25 11:16
Update: ``` swww-git ``` is not available in the chaotic so it would take time compiling.

We can wait for the fix,  the dev for swww is active.

**Comment by dieBakterie** [comment] 2024-03-25 11:20
I'm compiling it right now noo

**Comment by dieBakterie** [comment] 2024-03-25 11:22
Then i hope `swww-git` doesn't have errors

**Comment by dieBakterie** [comment] 2024-03-25 11:45
Then i hope `swww-git` has no errors. Update Same problem here.

**Comment by kRHYME7** [comment] 2024-03-25 15:21
@Sveen 
@dieBakterie 

I am also experiencing this issue. 

Here's a workaround in your ./userprefs.conf add this ``` exec-once = swww init ``` 
For now ``` swww init ``` is deprecated but still available so we can use it to remove the socket.   

Here's the reason.  The older /socket is still available after logout, giving errors like this

```
Error: "couldn't bind socket: Address already in use (os error 98)"
```
  


![image](https://github.com/prasanthrangan/hyprdots/assets/53417443/c2c37455-45a0-4edd-bcbd-85b1c4d02aae)




``` 
rm /run/user/1000/swww.socket    
swww-daemon
``` 

 can also work

**Comment by nicolkrit999** [comment] 2024-03-25 23:27
> Should i Go with swww or with swww-git i want avoid this issue and it's kinda related it's the chaotic aur(paru) First time using Not yay so. Thanks for the Help in advance and of course for the great project's

Switch to swww-git

**Comment by kRHYME7** [comment] 2024-03-27 14:06
https://github.com/LGFae/swww/commit/820ea906acf0f9d86e808303917c1f18ae914d2c

Move to  https://github.com/prasanthrangan/hyprdots/discussions/1205 , to utilize replies.

**Closed by kRHYME7** 2024-03-27 14:06 UTC
Labels: bug, unrelated
